### ISSUE TITLE
Манул считает "подозрительными" jQuery. Это нормально?

### ISSUE THREAD

**Issue by KarelWintersky** [antimalware/manul#101]
```
./template.bootstrap24/jquery-1.11.0.js
./core/js/jquery-1.10.2.min.js
./core/js/jquery-ui-1.10.3.custom.min.js
./core/js/jquery-ui-1.10.4.min.js
./core/js/filemanager/js/jquery.ui.position.js
./core/js/filemanager/js/jquery-ui-1.10.4.custom.js
etc
```

**Comment by peter-volkov** [comment]
Давайте посмотрим на сами файлы. По названию мало о чём можно сказать.

**Comment by KarelWintersky** [comment]
http://rghost.ru/7F2W4bnFK

Ну смотрите.

**Comment by peter-volkov** [comment]
Благодарю, хотелось убедиться, что там нет постороннего содержимого. Будет исправлено.

**Comment by KarelWintersky** [comment]
На наличие (или отсутствие) постороннего содержимого я файлы проверил в первую очередь. :) 

Вообще-то ему там неоткуда было взяться, а манул я запустил чтобы проверить - он все так же глючит, как прежде или что-то изменилось?

Что-то изменилось, но ложные срабатывания никуда не делись.
