### ISSUE TITLE
Сравнение хешей без строгой типизации

### ISSUE THREAD

**Issue by akamajoris** [antimalware/manul#64]
Файл Auth.inc.php
Строка 65: `return ($password_hash_from_cookie == $password_hash);`
Заменить на `return ($password_hash_from_cookie === $password_hash);`
Подробности: http://stackoverflow.com/questions/22140204/why-md5240610708-is-equal-to-md5qnkcdzo

**Comment by peter-volkov** [comment]
Да. спасибо. В рабочей ветке поменял - пока не успел выложить

**Comment by peter-volkov** [comment]
Добавил.
