### ISSUE TITLE
Executor/Quarantine

### ISSUE THREAD

**Issue by Rendername** [antimalware/manul#76]
При лечении, выбранные файлы не перемещаются на карантин. 
Сообщение об их перемещении в карантин:
Файл [./wp-content/plugins/cbnet-ping-optimizer/cbnet-ping-optimizer.php] помещен в карантин
Файл [./wp-content/plugins/cbnet-ping-optimizer/include/options-pg.php] помещен в карантин
...
Но файлы остаются по своему прежнему пути.

error_reporting(1);
В логах не нашлось что-то, что могло бы приводить к ошибкам.
Может быть есть решение данной проблемы?

**Comment by peter-volkov** [comment]
Как минимум, надо добавить дополнительные проверки успешности и прав доступа.

**Comment by themoor** [comment]
Файлы, помещенные в карантин, не должны удаляться, они остаются на своем месте до выяснения.
