### ISSUE TITLE
Could not properly handle AJAX request "status":200

### ISSUE THREAD

**Issue by Nanotraktor** [antimalware/manul#77]
При завершении сканирования ошибка: 
Could not properly handle AJAX request {"readyState":4,"responseText":"","status":200,"statusText":"OK"} 

![screen](https://cloud.githubusercontent.com/assets/12154674/7371612/bacb34e2-edca-11e4-8fe6-efbcc6d34e99.png)
В логах сервера ничего подозрительного: 

ххх.ххх.ххх.ххх - - [28/Apr/2015:18:43:09 +0300] "GET /manul-master/src/scanner/index.php?controller=scanner&a=getSignatureScanResult&delay=1 HTTP/1.1" 200 0 "http://609622.virusy.web.hosting-test.net/manul-master/src/scanner/index.php?controller=scanner" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
ххх.ххх.ххх.ххх - - [28/Apr/2015:18:43:09 +0300] "GET /manul-master/src/scanner/index.php?controller=scanner&a=getSignatureScanResult&delay=1 HTTP/1.1" 200 0 "http://609622.virusy.web.hosting-test.net/manul-master/src/scanner/index.php?controller=scanner" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
ххх.ххх.ххх.ххх - - [28/Apr/2015:18:43:09 +0300] "GET /manul-master/src/scanner/index.php?controller=scanner&a=getSignatureScanResult&delay=1 HTTP/1.1" 200 0 "http://609622.virusy.web.hosting-test.net/manul-master/src/scanner/index.php?controller=scanner" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"

Суммарно файлов в проверяемой папке - 35001

Не знаю, честно говоря, какая ещё информация нужна для поиска/устранения ошибки. 
Поэтому спрашивайте, могу дать всё вплоть до доступов для проверки.

**Comment by m-pokrovskii** [comment]
Такая же ошибка.

**Comment by peter-volkov** [comment]
Фикс будет через пару часов

**Comment by peter-volkov** [comment]
https://github.com/antimalware/manul/compare/malwareDetector_repackLog_hotfix

**Comment by Nanotraktor** [comment]
Большое спасибо, всё работает как часики.

**Comment by peter-volkov** [comment]
В мастер еще не добавлено.

**Comment by Nanotraktor** [comment]
Собственно, впервые использую github, поэтому вопрос. 
Стоит ли оставить открытым до добавления?

**Comment by peter-volkov** [comment]
Уже добавлено.

**Comment by m-pokrovskii** [comment]
Could not properly handle AJAX request {"readyState":4,"responseText":"XML path error filePath=/Applications/MAMP/htdocs/popsop-ru.lm/www/wp-client-test.php relativePath=./wp-client-test.php projectRootDir=/Applications/MAMP/htdocs/popsop-ru.lm/www/manul/src/scanner docRoot=/Applications/MAMP/htdocs/popsop-ru.lm/www","status":200,"statusText":"OK"}


Содержимое файла
```
<?php
if (!isset($HTTP_RAW_POST_DATA))
   $HTTP_RAW_POST_DATA = file_get_contents("php://input");
$x = trim($HTTP_RAW_POST_DATA);
print_r ($x);
/*
function _log($msg) {
	$fp = fopen('wp-client-test-log.txt', "a+");
	$date = gmdate("Y-m-d H:i:s ");
	$iot = "Input: \n";
	fwrite($fp, "\n\n" . $date . " " . $iot . $msg);
	fclose($fp);
}

_log('Проверка сервера');
*/
?>
```
Также спотыкается на простых файлах содержащих что-то вроде `<php echo 'world' ?>`
