### ISSUE TITLE
White list generator

### ISSUE THREAD

**Issue by d3th** [antimalware/manul#87]
You have a tool for creating white lists for Manul?

**Comment by themoor** [comment]
Hi! Not at the moment, but it's in the plans.

**Comment by d3th** [comment]
I have a working version. Send a PR?

**Comment by peter-volkov** [comment]
Sure. Let's see

**Comment by peter-volkov** [comment]
Well, seems cool, but I prefer to make it as a static page without a server-side. So it can be placed as github pages just as log analyzer.
It will allow anybody to generate whitelist for custom CMS easily or to make a whitelist for popular CMS to send a pull request. Queit a dilemma: you've got a working version and it is always better than promises, but is not easy to use. What we will do: if I will not finish the client-side-only whitelist generator by the beginning of the next week I will merge it, till I finish planned wl generator

**Comment by d3th** [comment]
All right. I think that a console utility will also be useful. Maybe develop it separately?

**Comment by peter-volkov** [comment]
Maybe you will develop it as standalone utility and I will make a link to it in readme.rd of whitelist repo?

**Comment by d3th** [comment]
Yep. No problem
