### ISSUE TITLE
PHP ZIP module

### ISSUE THREAD

**Issue by yakshov** [antimalware/manul#92]
unfortunately, my server owner can not add PHP ZIP module to server. so I can not use manul to check and heal my website :( .
Is there some other way for me?

**Comment by peter-volkov** [comment]
At the moment - no way, unfortunately. ZipArchive module is a standard PHP module and ita absence it absolutely rare anomaly. Althogh the purpose of Manul is to require minimum dependencies of the server environment, I'm not sure that it is a good idea to get rid of such minimalistic dependency as ZipArchive. Will think about it if some other cases will occur - at the moment, you're the first with this issue. Sorry
